version: '3'
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/dog_breeds
      - DOG_API_KEY=${DOG_API_KEY}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - BASE_IMAGE_URL = ${BASE_IMAGE_URL}
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dog_breeds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: